name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build -t adityajoshi1222/testing-image:v1 .
    - name: Push the Docker image
      run: docker push adityajoshi1222/testing-image:v1 
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: action/checkout@v3
    - name: deploying the application inside pod
      run:  kubectl create deployment myapp --image=testing-image



